services:
  - type: worker
    name: sage-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_KEY
        value: mrafrix
      - key: BASE_URL
        value: https://apis.sage.dpdns.org/api/v1
